version: "3.7"
services:
  backend:
    build: ./backend
    container_name: nestjs-backend
    command: npm run start:dev
    volumes:
      - ./backend/src:/code/src
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: nestjs-frontend
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/code/src

  nestjs-postgres:
    image: postgres:13
    container_name: nestjs-postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - nestjs-postgres:/var/lib/nestjs-postgres/data

volumes:
  nestjs-postgres: ~